models/News.php
<?php

namespace app\models;

use amnah\yii2\user\models\Profile;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property int $status
 * @property string $full_text
 * @property string $short_text
 * @property string $picture_path
 * @property string $name
 * @property int $profile_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Profile $profile
 * @property UploadedFile $image
 */
class News extends \yii\db\ActiveRecord
{
    public $image;

    const PICTURE_UPLOAD_DIR = 'user/photo/';
    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 2;

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => function () {
                    return gmdate("Y-m-d H:i:s");
                },
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'short_text', 'profile_id'], 'required'],
            [['status', 'profile_id'], 'integer'],
            [['full_text', 'short_text'], 'string'],
            [['image', 'created_at', 'updated_at'], 'safe'],
            [['picture_path', 'name'], 'string', 'max' => 255],
            [['image'], 'file', 'extensions' => 'jpg, gif, png'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('custom', 'ID'),
            'status' => Yii::t('custom', 'Status'),
            'full_text' => Yii::t('custom', 'Full Text'),
            'short_text' => Yii::t('custom', 'Short Text'),
            'picture_path' => Yii::t('custom', 'Picture Path'),
            'name' => Yii::t('custom', 'Name'),
            'image' => Yii::t('custom', 'Image'),
            'profile_id' => Yii::t('custom', 'Profile ID'),
            'created_at' => Yii::t('custom', 'Created At'),
            'updated_at' => Yii::t('custom', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfile()
    {
        return $this->hasOne(Profile::className(), ['id' => 'profile_id']);
    }

    public function namePicture()
    {
        $this->picture_path = Yii::$app->security->generateRandomString();

        return self::getPictureDest($this->picture_path);
    }

    public static function getPictureDest($name)
    {
        $base_path = Yii::getAlias('@app') . '/uploads/' . self::PICTURE_UPLOAD_DIR;
        if (!is_null($name)) {
            return $base_path . $name;
        } else {
            return $base_path . 'default';
        }
    }

    public static function getImage($name)
    {
        $file_path = self::getPictureDest($name);
        if (file_exists($file_path)) {
            return file_get_contents($file_path);
        }
        return null;
    }


    public static function getStatuses()
    {
        return [
            self::STATUS_ACTIVE => Yii::t('custom', 'Active'),
            self::STATUS_INACTIVE => Yii::t('custom', 'Deactive')
        ];
    }

    public function isActive()
    {
        return $this->status == self::STATUS_ACTIVE;
    }

    public function changeStatus($status)
    {
        if ($this->status == $status) {
            return true;
        } else {
            $this->status = $status;
            return $this->save();
        }
    }


}

controllers/NewsController.php
<?php

namespace app\controllers;

use app\models\User;
use app\utils\PermissionHelper;
use Yii;
use app\models\News;
use app\models\search\NewsSearch;
use yii\bootstrap\ActiveForm;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'picture'
                        ],
                        'allow' => true,
                    ],
                    [
                        'allow' => true,
                        'actions' => ['view'],
                        'roles' => ['@']
                    ],
                    [
                        'actions' => [
                            'create',
                            'update',
                            'delete',
                            'validate',
                            'status'
                        ],
                        'roles' => [User::ROLE_MANAGER],
                        'allow' => true,
                    ],
                    [
                        'allow' => false
                    ]
                ],
            ],
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (!is_null($per_page = Yii::$app->request->get('per-page'))) {
            Yii::$app->session->set('per-page', $per_page);
        }
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new News();
        $model->profile_id = Yii::$app->user->identity->profile->id;
        if ($model->load(Yii::$app->request->post())) {
            $image = UploadedFile::getInstance($model, 'image');
            if (!is_null($image)){
                $path = $model->namePicture();
            }
            if ($model->save()) {
                if (isset($path)) {
                    $image->saveAs($path);
                }
                return $this->renderAjax('@app/views/layouts/ajax_result', [
                    'message' => Yii::t('custom', 'News save')
                ]);
            }
        }
        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }


    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        if (!Yii::$app->user->can(PermissionHelper::PERMISSION_EDIT_NEWS, ['news_id' => $id])) {
            throw new ForbiddenHttpException(Yii::t('app', 'Permission dehined'));
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $image = UploadedFile::getInstance($model, 'image');
            if (!is_null($image)){
                $path = $model->namePicture();
            }
            if ($model->save()) {
                if (isset($path)) {
                    $image->saveAs($path);
                }
                return $this->renderAjax('@app/views/layouts/ajax_result', [
                    'message' => Yii::t('custom', 'News save')
                ]);
            }
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }


    /**
     * @param $path
     * @return $this
     * @throws NotFoundHttpException
     */
    public function actionPicture($name=null)
    {
        if ($content = News::getImage($name)) {
            return Yii::$app->response->sendContentAsFile($content, $name);
        }
        throw new NotFoundHttpException(Yii::t('Error messages', 'File not found'));
    }


    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionDelete($id)
    {
        if (!Yii::$app->user->can(PermissionHelper::PERMISSION_EDIT_NEWS, ['news_id' => $id])) {
            throw new ForbiddenHttpException(Yii::t('app', 'Permission dehined'));
        }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionStatus($id, $status)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (!ArrayHelper::isIn($status, array_keys(News::getStatuses()))) {
            return [
                'status' => 'error',
                'message' => Yii::t('app', 'Status not support')
            ];
        }
        $news = $this->findModel($id);
        if ($news->changeStatus($status)) {
            if ($news->isActive()) {
                $result = [
                    'message' => Yii::t('custom', 'Deactivate'),
                    'status_id' => News::STATUS_INACTIVE
                ];
            } else {
                $result = [
                    'message' => Yii::t('custom', 'Activate'),
                    'status_id' => News::STATUS_ACTIVE
                ];
            }
            return ArrayHelper::merge($result, [
                'status' => 'success',
            ]);
        } else {
            return [
                'status' => 'error',
                'message' => Yii::t('app', 'Status not change')
            ];
        }
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionValidate($id = null)
    {
        if (is_null($id)) {
            $news = new News();
        } else {
            $news = $this->findModel($id);
        }
        $post = Yii::$app->request->post();
        if (Yii::$app->request->isAjax && $news->load($post)) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($news);
        }
    }
}

views/news/_form.php
<?php

use app\models\News;
use kartik\file\FileInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\News */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-form">

    <?php $form = ActiveForm::begin([
        'action' => Yii::$app->request->absoluteUrl,
        'options' => [
            'id' => 'news_create_form',
            'enctype' => 'multipart/form-data'
        ],
        'enableAjaxValidation' => true,
        'enableClientValidation' => false,
        'validationUrl' => ['validate', 'id' => $model->id]
    ]); ?>

    <?= $form->field($model, 'status')->dropDownList(News::getStatuses()) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'full_text')->textarea(['rows' => 3]) ?>

        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'short_text')->textarea(['rows' => 3]) ?>
        </div>
    </div>

    <?= $form->field($model, 'image')->widget(FileInput::classname(), [
            'options' => ['accept' => 'image/*'],
            'pluginOptions' => [
                'allowedFileExtensions' => ['jpg', 'gif', 'png'],
                'showPreview' => false,
                'showCaption' => true,
                'showRemove' => false,
                'uploadAsync' => false,
                'dropZoneEnabled' => false,
                'showUpload' => false,
            ]
        ]
    ); ?>

    <div class="form-group">
        <?= Html::button(Yii::t('custom', 'Save'), ['class' => 'file-modal-submit btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/news/_item.php
<?php


/* @var $this yii\web\View */

use app\models\News;
use app\utils\PermissionHelper;
use yii\bootstrap\Html;

/* @var $model app\models\News */
?>

<div class="row">

    <div class="panel panel-default">
        <div class="panel-heading">
            <?= $model->name ?>
        </div>
        <div class="panel-body">
            <?= Html::img(['/news/picture', 'name' => $model->picture_path],['class'=>'news-picture']) ?>
            <?php if (Yii::$app->user->isGuest) : ?>
                <?= $model->short_text ?>
            <?php else : ?>
                <?= $model->full_text ?>
            <?php endif; ?>

            <?php if (Yii::$app->user->can(
                PermissionHelper::PERMISSION_EDIT_NEWS,
                ['news_id' => $model->id])
            ) : ?>
                <?= Html::a('', ['/news/update', 'id' => $model->id],
                    [
                        'class' => 'glyphicon glyphicon-pencil',
                        'data-target' => '#remote_modal',
                        'data-toggle' => 'modal'
                    ]); ?>
                <?= Html::a('', ['/news/delete', 'id' => $model->id],
                    [
                        'class' => 'glyphicon glyphicon-trash',
                        'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                        'data-method' => 'post',
                    ]); ?>
                <?= Html::a('', ['/news/view', 'id' => $model->id],
                    [
                        'class' => 'glyphicon glyphicon-eye-open',
                    ]); ?>
                <?= Html::button(($model->isActive()) ? Yii::t('custom', 'Deactivate')
                    : Yii::t('custom', 'Activate'),
                    [
                        'data-id' => $model->id,
                        'data-status_id' => ($model->isActive()) ? News::STATUS_INACTIVE : News::STATUS_ACTIVE,
                        'class' => 'news-status btn btn-default',
                    ]); ?>
            <?php endif; ?>
        </div>
    </div>


</div>

views/news/_search.php
<?php

use app\models\News;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\NewsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?php if (!Yii::$app->user->isGuest): ?>
        <?= $form->field($model, 'status')->dropDownList(News::getStatuses()) ?>
    <?php endif; ?>
    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'date_from') ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'date_to') ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('custom', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('custom', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/news/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = Yii::t('custom', 'Create News');
$this->params['breadcrumbs'][] = ['label' => Yii::t('custom', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-create">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">&times;</span>
        </button>
        <div class="modal-title">
            <?= Html::encode($this->title) ?>
        </div>
    </div>
    <div class="modal-body">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

views/news/index.php
<?php

use app\models\User;
use yii\bootstrap\BaseHtml;
use yii\bootstrap\Dropdown;
use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\NewsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('custom', 'News');
$this->params['breadcrumbs'][] = $this->title;
$view = $this;
$items = [];
for ($index = 0; $index < 20; $index += 5) {
    if ($index == 0) {
        $item_count = $index + 1;
    } else {
        $item_count = $index;
    }
    $items[] = [
        'label' => Yii::t('custom', 'Show') . ' ' . $item_count,
        'url' => ['/news/index', 'per-page' => $item_count]
    ];
}

?>
<div class="news-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <div class="dropdown">
        <a href="#" data-toggle="dropdown"
           class="btn btn-default dropdown-toggle"><?= Yii::t('custom', 'Page item count') ?><b class="caret"></b></a>
        <?php
        echo Dropdown::widget([
            'items' => $items,
        ]);
        ?>
    </div>
    </br>

    <?php if (Yii::$app->user->can(User::ROLE_MANAGER)): ?>
        <p>
            <?= Html::a(
                Yii::t('custom', 'Create News'),
                ['create'],
                [
                    'class' => 'btn btn-success',
                    'data-target' => '#remote_modal',
                    'data-toggle' => 'modal'
                ]
            ) ?>
        </p>
    <?php endif; ?>
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemOptions' => ['class' => 'item'],
        'itemView' => function ($model, $key, $index, $widget) use ($view) {
            return $view->render('_item', ['model' => $model]);
        },
    ]) ?>
</div>

views/news/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = Yii::t('custom', 'Update News: {nameAttribute}', [
    'nameAttribute' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('custom', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="news-update">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">&times;</span>
        </button>
        <div class="modal-title">
            <?= Html::encode($this->title) ?>
        </div>
    </div>
    <div class="modal-body">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

views/news/view.php
<?php

use app\utils\PermissionHelper;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('custom', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->user->can(
        PermissionHelper::PERMISSION_EDIT_NEWS,
        ['news_id' => $model->id])
    ) : ?>
        <p>
            <?= Html::a(Yii::t('custom', 'Update'),
                ['update', 'id' => $model->id],
                [
                    'class' => 'btn btn-success',
                    'data-target' => '#remote_modal',
                    'data-toggle' => 'modal'
                ]) ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    <?php endif; ?>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'full_text:ntext',
            'short_text:ntext',
            'name',
            'created_at:datetime',
        ],
    ]) ?>

</div>